#!/usr/bin/php
<?php

function get_random_day() {
    $year = mt_rand(2010,2015);
    $month = mt_rand(1,12);
    $day = mt_rand(1, 28);
    return sprintf(
        "%s-%s-%s 00:00:00",
        $year,
        $month,
        $day
    );
}

function flush_query($insert_values) {
    if (empty($insert_values)) return;
    print sprintf(
        "insert into mo values %s;\n",
        join(",", $insert_values)
    );
}

$insert_values = array();
for($c = 1; $c <= (int)$argv[1]; $c++) {
    $date = get_random_day();
    $v = array('test data', 'on game', 'game news', 'stop game', 'stop all', 'on forum', 'stop forum');
    $insert_values[] = "(NULL,'1111111','1','2','".$v[ $c % count($v) ]."','token','{$date}')";
    if ($c % 10000 === 0) {
        flush_query($insert_values);
        $insert_values = array();
    }
}

flush_query($insert_values);
